
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjvieilnhyfryhszgvtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqdmllaWxuaHlmcnloc3pndnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTg2MTMsImV4cCI6MjA2MjAzNDYxM30.gdGY8Up5gWm21e3CXWrZ50420NnhZYbp6DM1HdKJMMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Solución temporal: función helper modificada para evitar errores de tipo
export const fromTable = <T extends object>(tableName: string) => {
  return supabase.from(tableName) as any;
};
